initial_situation: |
  The party stands at the entrance of the Crimson Crypt, an ancient tomb recently uncovered in the forests north of the city.
  Local legends speak of powerful magical artifacts sealed away here centuries ago...
